### ISSUE TITLE
bug of IS_CONSTANT in php 7

### ISSUE THREAD

**Issue by fzxcp3** [derickr/vld#32]
srm_oparray.c:448:8: error: 'IS_CONSTANT' undeclared (first use in this function)
case IS_CONSTANT:       return vld_dump_zval_constant (val.value)
IS_CONSTANT type and Z_CONST_FLAGS() are removed. Now constants are always represented using IS_CONSTANT_AST
so it's undeclared

**Comment by derickr** [comment]
In which PHP version is that? It still compiles with PHP 7.2.0-dev.

**Comment by fzxcp3** [comment]
PHP 7.3.0-dev
the newest version in https://github.com/php/php-src

**Comment by derickr** [comment]
This is been resolve in the meanwhile.
